# Generated by Django 4.2.7 on 2024-01-20 10:15

import affiliate.models
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_ar', models.CharField(max_length=200)),
                ('city_name_en', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_name_ar', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('طلبات معلقة', 'طلبات معلقة'), ('طلبات ملغيه', 'طلبات ملغيه'), ('طلبات مؤجلة', 'طلبات مؤجلة'), ('طلبات جاري التحضير', 'طلبات جاري التحضير'), ('طلبات ملغية اثناء التحضير', 'طلبات ملغية اثناء التحضير'), ('طلبات تم الشحن', 'طلبات تم الشحن'), ('طلبات تم التوصيل', 'طلبات تم التوصيل'), ('طلبات استرجاع من العميل', 'طلبات استرجاع من العميل'), ('طلبات مرتجعة بعد التوصيل', 'طلبات مرتجعة بعد التوصيل'), ('جار الاسترجاع', 'جار الاسترجاع'), ('مرتجع', 'مرتجع')], default='طلبات معلقة', max_length=255)),
                ('barcode', models.CharField(default=affiliate.models.generate_unique_barcode, max_length=10, unique=True)),
                ('barcode_returned', models.CharField(default=affiliate.models.generate_unique_barcode_returned, max_length=11)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone1', models.CharField(max_length=255)),
                ('client_phone2', models.CharField(max_length=255)),
                ('client_address', models.TextField()),
                ('shiping_price', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('total_items_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField()),
                ('whats1_clicked', models.IntegerField(default=0)),
                ('phone1_clicked', models.IntegerField(default=0)),
                ('sms1_clicked', models.IntegerField(default=0)),
                ('whats2_clicked', models.IntegerField(default=0)),
                ('phone2_clicked', models.IntegerField(default=0)),
                ('sms2_clicked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='governorate', chained_model_field='governorate', on_delete=django.db.models.deletion.CASCADE, to='affiliate.city')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=255)),
                ('barcode', models.CharField(default=affiliate.models.generate_unique_barcode, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_to', models.ManyToManyField(limit_choices_to={'is_marketer': True}, related_name='access_to_this_product', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.category')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliate.inventory')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='affiliate_s_name_86b676_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_set', to='affiliate.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.size')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='affiliate.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='affiliate.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='affiliate.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.shippingprice'),
        ),
        migrations.AddField(
            model_name='order',
            name='marketer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_marketer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.shippingcompany'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['name'], name='affiliate_i_name_973336_idx'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.governorate'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='affiliate_c_name_063833_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'access_type'], name='affiliate_p_name_387b87_idx'),
        ),
    ]
