# Generated by Django 4.2.6 on 2023-10-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product'},
        ),
    ]
