# Generated by Django 4.2.7 on 2024-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
