# Generated by Django 4.2.7 on 2024-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_alter_order_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barcode_returned',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
