# Generated by Django 4.2.6 on 2023-11-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_category_inventory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventories'},
        ),
    ]
