# Generated by Django 4.2.7 on 2024-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='action_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
