# Generated by Django 4.2.7 on 2024-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('vodafone', 'Vodafone Cash'), ('instapay', 'Insta Pay'), ('bank', 'Bank')], max_length=255, null=True),
        ),
    ]
