# Generated by Django 4.2.7 on 2024-02-13 06:45

import affiliate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0009_alter_order_barcode_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='access_to',
            field=models.ManyToManyField(blank=True, db_index=True, limit_choices_to={'is_marketer': True}, null=True, related_name='access_to_this_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, default=affiliate.models.generate_unique_barcode, max_length=10, unique=True),
        ),
    ]
