# Generated by Django 4.2.7 on 2023-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0010_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='affiliate_s_name_86b676_idx')],
            },
        ),
    ]
