# Generated by Django 4.2.7 on 2024-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0011_remove_request_phone_request_bank_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='bank_field',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='instapay_field',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vodafone_field',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
