# Generated by Django 4.2.7 on 2023-11-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0013_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_name_ar', models.CharField(max_length=50)),
                ('governorate_name_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_ar', models.CharField(max_length=200)),
                ('city_name_en', models.CharField(max_length=200)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.governorate')),
            ],
        ),
    ]
