# Generated by Django 4.2.7 on 2024-02-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0013_alter_request_bank_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('جار مراجعة', 'جار مراجعة'), ('تم الموافقة', 'تم الموافقة'), ('تم الرفض', 'تم الرفض')], default='جار مراجعة', max_length=255),
        ),
    ]
