# Generated by Django 4.2.7 on 2024-02-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0014_alter_request_amount_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
