# Generated by Django 4.2.7 on 2023-11-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0016_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='governorate_name_en',
        ),
    ]
