# Generated by Django 4.2.7 on 2023-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0017_remove_governorate_governorate_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governorate',
            name='governorate_name_ar',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
