# Generated by Django 4.2.7 on 2024-02-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0017_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
