# Generated by Django 4.2.7 on 2023-11-27 14:58

import affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0018_alter_governorate_governorate_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=affiliate.models.generate_unique_barcode, max_length=8, unique=True),
        ),
    ]
