# Generated by Django 4.2.7 on 2023-12-03 00:27

import affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0022_color_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=affiliate.models.generate_unique_barcode, max_length=10, unique=True),
        ),
    ]
