# Generated by Django 4.2.7 on 2023-12-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0023_product_additional_attributes_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='affiliate.OrderItem', to='affiliate.product'),
        ),
    ]
