# Generated by Django 4.2.7 on 2023-12-03 17:19

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0029_remove_product_additional_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='shipping_governorate', chained_model_field='governorate', on_delete=django.db.models.deletion.CASCADE, to='affiliate.city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'طلبات معلقة'), ('preparation', 'طلبات جاري التحضير'), ('shipped', 'طلبات تم الشحن'), ('delivered', 'طلبات تم التوصيل'), ('return_in_progress', 'جار الاسترجاع'), ('canceled', 'طلبات ملغيه'), ('post_delivery_return', 'طلبات مرتجعة'), ('returned', 'طلبات مرتجعة بعد التسليم'), ('returned_after_delivery', 'طلبات مرتجعة بعد التوصيل'), ('deferred', 'طلبات مؤجله')], default='pending', max_length=255),
        ),
    ]
