# Generated by Django 4.2.7 on 2023-12-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0030_alter_order_city_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.governorate'),
        ),
    ]
