# Generated by Django 4.2.7 on 2023-12-03 18:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0031_alter_order_shipping_governorate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_governorate',
            new_name='governorate',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='governorate', chained_model_field='governorate', on_delete=django.db.models.deletion.CASCADE, to='affiliate.city'),
        ),
    ]
