# Generated by Django 4.2.7 on 2023-12-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0033_alter_order_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.governorate'),
        ),
    ]
