# Generated by Django 4.2.7 on 2023-12-04 00:16

import affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0034_alter_order_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barcode',
            field=models.CharField(default=affiliate.models.generate_unique_barcode, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'access_type'], name='affiliate_p_name_387b87_idx'),
        ),
    ]
