# Generated by Django 4.2.7 on 2023-12-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0035_alter_order_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.shippingprice'),
        ),
    ]
