# Generated by Django 4.2.7 on 2023-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0036_remove_order_shipping_remove_orderitem_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
