# Generated by Django 4.2.7 on 2023-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0037_orderitem_total_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
