# Generated by Django 4.2.7 on 2023-12-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0038_order_total_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_items', through='affiliate.OrderItem', to='affiliate.product'),
        ),
    ]
