# Generated by Django 4.2.7 on 2023-12-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0040_orderitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total',
            new_name='total_items_price',
        ),
    ]
