# Generated by Django 4.2.7 on 2023-12-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0041_rename_total_orderitem_total_items_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_items_price',
            new_name='total',
        ),
    ]
