# Generated by Django 4.2.7 on 2023-12-06 23:49

import affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0044_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode_returned',
            field=models.CharField(default=affiliate.models.generate_unique_barcode_returned, max_length=11),
        ),
    ]
