# Generated by Django 4.2.7 on 2023-12-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0045_order_barcode_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
