# Generated by Django 4.2.7 on 2023-12-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0046_product_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_price',
        ),
    ]
