# Generated by Django 4.2.7 on 2023-12-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0047_remove_product_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
