# Generated by Django 4.2.7 on 2023-12-12 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0050_alter_product_access_to'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='affiliate_o_client__d4c4e2_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='affiliate.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
