# Generated by Django 4.2.6 on 2023-11-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Marketer',
            new_name='is_marketer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Vendor',
            new_name='is_vendor',
        ),
    ]
