# Generated by Django 4.2.7 on 2023-12-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_allow_upload_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
